### ISSUE TITLE
Base Management Platform Launch Requirements

### ISSUE THREAD

**Issue by solocommand** [cygnusb2b/base-platform-issues#1]
# Remaining
## Bugs
- [x] New url structure is missing; articles on Nfocus are as follows:  http://www.nfocusnashville.com/content/article/13227734/symphony-show-house
- [ ] ***CH*** Dirty model on timePicker change :exclamation:
- [x] Phone and email fields are missing from contacts cygnusb2b/base-platform#609
- [x] Fix 500 after event submission :exclamation:
- [x] update event submission fields (misspellings and all fields should not be required)
- [x] hide contact field keys if the values aren't set (Contact Us listing)
- [x] fix calendar page on "tablet" screen size
- [x] ***(JB)*** Add event subscriber for new schedules to set content fields :exclamation:

## Cleanup
- [x] Remove all Featured Content schedules that were created during import
- [x] Add command to infer primarySection/primarySite from scheduling, where possible. (cygnusb2b/base-platform#592)
- [x] Nfocus Nashville Redirects: cygnusb2b/base-platform#611
  - [x] /nashville-nfocus-magazine-home to /
  - [x] /home to /
  - [x] /nashville-nfocus-weddings to /people-places/weddings
  - [x] /nashville-nfocus-lifestyle to /style
  - [x] /nashville-nfocus-features to /
  - [x] /advertise_nfocus_magazine to /advertise
  - [x] /nashville-nfocus-photos to /events
  - [x] /model-behavior to /style/fashion
  - [x] /epicurean to /food-drink
  - [x] /faq to /contact-us
  - [x] /weddings to /people-places/weddings
  - [x] /contact-nfocus-magazine to /contact-us

## Website
- [ ] Update Media kit (Nancy to provide), unless she can do it herself...?

- [ ] Take care of "Should Fix" recommendations from [Google PageSpeed] (https://developers.google.com/speed/pagespeed/insights/?url=www.nfocusnashville.com&tab=desktop)
- [ ] Mobile recommendations [from Google] (https://developers.google.com/speed/pagespeed/insights/?url=www.nfocusnashville.com&tab=mobile)
- [ ] Remove or hide "Load More" if there are no more results to display.  Also remove the message that says "NO ADDITIONAL CONTENT FOUND" (its unnecessary)
- [x] Enable Nfocus Advertise link in footer (says disabled)
- [x] Update Nfocus site title capitalization (Change from nFocus to Nfocus)
- [x] ***(BM)*** Check Nfocus logo quality - pixelated according to Nancy -- extract from PSD, existing was pulled from JPG of design.
- [ ] Check thumbnail jpeg quality settings; they appear blurry (see "Taking Vows" in Wedding block within People and Places channel for example)
  - [ ] These were thumbnails embedded in body copy and **may** be duplicates of images on content. Delete?
- [ ] Cross browser testing
  - [ ] latest IE
  - [x] Firefox
  - [x] Chrome
  - [x] Safari
  - [x] Opera
- [x] ***(JB)*** Turn on auto trigger of load more on content pages, channel pages (two triggers on both).  Home stays at zero.
- [ ] SEO
  - [x] Redirect non-www to www
  - [x] ***(JW)*** Sitemap
  - [ ] ***(JL)*** Meta descriptions, Title tags, etc
  - [ ] ***(JL)*** Webmaster Tools recommendations
  - [x] ***(JL)*** Robots.txt
    - [x] Add no follow on load-more urls
  - [ ] ***(BK)*** Verify rel=canonical, channel urls / logic
  - [x] List and handle non-content 301 redirects (legacy sections)
- [x] ***(CK)*** Pretty 500/404 pages
- [x] ***(JB)*** Scheduling
  - [x] "The Latest" block should also include content scheduled to sub-channels, not just the parent
  - [x] Channel block scheduling = match section page
  - [x] Ensure 'latest' block returns unique content if scheduled to multiple sections.
    - [x] Same for home page "Load More" results
- [x] Add byline to content (don't link until Author page is complete)
- [ ] Magazine Issue Page, Current Issue Block
- [x] Add Contacts to Contact Us page (in order)
 - [x]  Nancy Floyd - 13227554
 - [x]  Heather Pierce - 13227785
 - [x]  Kendall Gemmill - 13227590
 - [x]  Abby White - 13227568
 - [x]  Mike Smith - 13227784
 - [x]  Maggie Bond - 13002862
- [ ] Author / Contributor landing page
- [ ] Document content type / download landing page
- [ ] Newsletter sign-up page, re-enable in footer
- [x] Add submit Event button (get from Ryan W)
- [x] Related Content algorithm / fallback logic
- [ ] New blocks
  - [ ] Subscribe block (social media?)
  - [ ] Additional Resources

## CMS
- [ ] Add Hootlet into CMS
- [ ] Add shortcut/helper for adding primary section scheduling (on Publish?)
- [ ] Article Export to InDesign (Article Text, Collected Article)
- [ ] Out of date/refresh for latest changes warning bar
  - Some sort of heartbeat detection; determine if the loaded `framework_version` (inject to config) has changed on the server. Create /heartbeat handler that returns the current `framework_version`. If version in current config is not the same, display an orange bar below the top nav that warns the user 'Base Platform Update: Save changes and [reload](#) to access the newest features.'
- [ ] Soft delete & change history to Modlr
- [ ] Store requested URI on auth fail/timeout and redirect after login if available.
- [ ] ***(JW)*** Organization/Venue: Add edit icon to existing ref'd entities and create new button on field. Open both in modal. Edit saves/closes modal, create saves & relates to ref field.
- [ ] ~~SouthComm~~ **Auth0** authentication
- [ ] Embedded images in content body
- [ ] Image Active/Approved (do we still need this?)
- [ ] Mutation support
- [ ] Dynamic form generation

## After nFocus
- [ ] Dashboard landing page
- [ ] Website management
- [ ] Print management
- [ ] Newsletter management
- [ ] Contracts Application
- [ ] Add bulk edit to related media (i.e. change credit for multiple images at once)

# Completed
## CMS
- [x] Browse Scheduling
- [x] Content Scheduling
- [x] Image Upload & Crop
- [x] Primary Image
- [x] Status management (published, draft, etc.)
- [x] Final content import
  - [ ] [BASE-1514] (http://workflow.cygnus.com/browse/BASE-1514) Content: Update notes field to support simple html (`p, em, strong, i, u, sub`)
  - [ ] [BASE-1517] (http://workflow.cygnus.com/browse/BASE-1517) Replace break tags with paragraph tags on paste
  - [x] [BASE-1518] (http://workflow.cygnus.com/browse/BASE-1518) Content: Add global loading and button "lock" while processing :exclamation: 
- [x] Add primary channel dropdown (possibly under primary site?)
- [x] cygnusb2b/base-platform#530 Scheduling SubscriberPass
- [x] Reverse UTF8/HTMLEntities encoding for non-body fields
- [x] Unsupported Browser Page
- [x] Analytics
- [x] Advertising
  - [x] Support serving DFP ads
  - [x] Page Context replacement
- [x] Remove imported MNI images
- [x] Update URI format: cygnusb2b/base-platform#574
- [x] Ember Manager wrapper
- [x] Finalize content create (config based primary mutation)?

## Bugs
  - [x] [BASE-1498] (http://workflow.cygnus.com/browse/BASE-1498) Content: Verify field display and order for content types & mutations
  - [x] [BASE-1509] (http://workflow.cygnus.com/browse/BASE-1509) Content: Bind images to crop modification
- [x] Auto select schedule product if only 1 exists globally
- [x] Set Standard Web option as default for website scheduling (create)
- [x] Display section hierarchy on website sections
- [x] Author autocomplete, display full name after selection
- [x] Allow user to set published date on status change
- [x] Set status to draft (deleted?) -> clear published date
- [x] New schedule start date should match published date by default (works on page re-load)
- [x] Clear primary image if the aspect ratio changes from landscape
- [x] Add time picker to published/unpublished & scheduling (start/end)
  - [x] Update datepicker on events
- [x] Updating Contact First and Last Name needs to update full name
- [x] Adjust "All Day" input on Events so that only the check box & label are clickable
- [x] Prevent double-clicking schedule add; disable on submit.
- [x] Support setting primarySection for single- and multi-site scenarios. Possible solution: Link field to primarySite, remove when linked field changes. Only return in `ContentController::getReferringPage()` if the set section belongs to the currently accessed site.
 - [x] Set Max height (overflow-y: scroll) on select drop downs (i.e. Schedule Section)
 - [x] Add clear button to schedule create

**Comment by solocommand** [comment]
@brandonbk "Sort by Published date does not appear to be working correctly in the CMS"

Details on this? Appears to be working correctly to me...

**Comment by curthusting** [comment]
@solocommand @B77Mills @zarathustra323 @Jlaird @CaitlynKnudsvig 
Can everyone take a minute and check off all tasks that are complete so I can transfer this monstrosity into individual issues
