### ISSUE TITLE
Nfocus Nashville Punch List

### ISSUE THREAD

**Issue by brandonbk** [cygnusb2b/base-platform-issues#10]
# Remaining
## Website
- [ ] Consideration for how to display "Photographs by..." byline
- [ ] Nstyle content - better way of displaying?
- [ ] Newsletters

# Completed

## Website
- [x] Swan Ball - Custom Fotomoto integration @B77Mills  in progress
- [x] Magazine, Current Issue
- [x] Mobile recommendations [from Google] (https://developers.google.com/speed/pagespeed/insights/?url=www.nfocusnashville.com&tab=mobile)
- [x] **JL** Redirect nfocusmagazine.com to nfocusnashville.com
- [x] Exclude "event" content type from showing up on home page OR exclude Calendar channel content
- [x] Event Section page add 300x600 back in.
- [x] Event page cleanup [PR #706](/cygnusb2b/base-platform/pull/706)
  - [x] Cost and Address layout problem: http://www.nfocusnashville.com/calendar/event/13230051/father-of-the-year-awards
  - [x] "All Day" checkbox should disable (or not require?) a time to be set.  Display consideration should also be given to the site in this case.
  - [x] Change "Cost" label to "Tariff"...is this an option for Nfocus only? [PR #706](/cygnusb2b/base-platform/pull/706)
  - [x] Add field:  Beneficiary [PR #706](/cygnusb2b/base-platform/pull/706)
  - [x] Creation of Venues and Organizations
- [x] Update Media kit (Nancy to provide), unless she can do it herself...?
- [x] Enable Nfocus Advertise link in footer (says disabled)
- [x] Update Nfocus site title capitalization (Change from nFocus to Nfocus)
- [x] ***(BM)*** Check Nfocus logo quality - pixelated according to Nancy -- extract from PSD, existing 
  - [x] Redirect non-www to www
  - [x] ***(JW)*** Sitemap
  - [x] ***(JL)*** Robots.txt
- [x] Add Contacts to Contact Us page (in order)
 - [x]  Nancy Floyd - 13227554
 - [x]  Heather Pierce - 13227785
 - [x]  Kendall Gemmill - 13227590
 - [x]  Abby White - 13227568
 - [x]  Mike Smith - 13227784
 - [x]  Maggie Bond - 13002862

## Cleanup
- [x] Remove all Featured Content schedules that were created during import
- [x] Add command to infer primarySection/primarySite from scheduling, where possible. [PR #592](/cygnusb2b/base-platform/pull/592)
- [x] Nfocus Nashville Redirects: [PR #611](/cygnusb2b/base-platform/pull/611)
  - [x] /nashville-nfocus-magazine-home to /
  - [x] /home to /
  - [x] /nashville-nfocus-weddings to /people-places/weddings
  - [x] /nashville-nfocus-lifestyle to /style
  - [x] /nashville-nfocus-features to /
  - [x] /advertise_nfocus_magazine to /advertise
  - [x] /nashville-nfocus-photos to /events
  - [x] /model-behavior to /style/fashion
  - [x] /epicurean to /food-drink
  - [x] /faq to /contact-us
  - [x] /weddings to /people-places/weddings
  - [x] /contact-nfocus-magazine to /contact-us

**Comment by curthusting** [comment]
Closing this considering the remaining items are not actionable
